package generator

// Generator defines the interface that generates a sequence of string values,
// following some distribution (Uniform, Zipfian, Sequential, etc.)
type Generator interface {

	// NextString generates the next string in the distribution.
	NextString() string

	// LastString returns the previous string generated by the distribution;
	// e.g., returned from the last NextString() call.
	// Calling LastString() should not advance the distribution or
	// have any side effects. If NextString() has not yet been called,
	// LastString() should return something reasonable.
	LastString() string
}
